# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Temperature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Temperature.proto',
  package='temperatures',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11Temperature.proto\x12\x0ctemperatures\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"v\n\x0fTemperatureData\x12\x11\n\tdevice_ID\x18\x01 \x01(\t\x12-\n\tdate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x0c\n\x04unit\x18\x04 \x01(\t2^\n\x12TemperatureSensing\x12H\n\x12\x41\x64\x64TemperatureData\x12\x1d.temperatures.TemperatureData\x1a\x13.temperatures.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='temperatures.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=75,
)


_TEMPERATUREDATA = _descriptor.Descriptor(
  name='TemperatureData',
  full_name='temperatures.TemperatureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_ID', full_name='temperatures.TemperatureData.device_ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_time', full_name='temperatures.TemperatureData.date_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='temperatures.TemperatureData.temperature', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='temperatures.TemperatureData.unit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=195,
)

_TEMPERATUREDATA.fields_by_name['date_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['TemperatureData'] = _TEMPERATUREDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'Temperature_pb2'
  # @@protoc_insertion_point(class_scope:temperatures.Empty)
  })
_sym_db.RegisterMessage(Empty)

TemperatureData = _reflection.GeneratedProtocolMessageType('TemperatureData', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREDATA,
  '__module__' : 'Temperature_pb2'
  # @@protoc_insertion_point(class_scope:temperatures.TemperatureData)
  })
_sym_db.RegisterMessage(TemperatureData)



_TEMPERATURESENSING = _descriptor.ServiceDescriptor(
  name='TemperatureSensing',
  full_name='temperatures.TemperatureSensing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=197,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTemperatureData',
    full_name='temperatures.TemperatureSensing.AddTemperatureData',
    index=0,
    containing_service=None,
    input_type=_TEMPERATUREDATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATURESENSING)

DESCRIPTOR.services_by_name['TemperatureSensing'] = _TEMPERATURESENSING

# @@protoc_insertion_point(module_scope)
