# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Temperature_pb2 as Temperature__pb2


class TemperatureSensingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTemperatureData = channel.unary_unary(
                '/temperatures.TemperatureSensing/AddTemperatureData',
                request_serializer=Temperature__pb2.TemperatureData.SerializeToString,
                response_deserializer=Temperature__pb2.Empty.FromString,
                )


class TemperatureSensingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTemperatureData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureSensingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTemperatureData': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTemperatureData,
                    request_deserializer=Temperature__pb2.TemperatureData.FromString,
                    response_serializer=Temperature__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperatures.TemperatureSensing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TemperatureSensing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTemperatureData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/temperatures.TemperatureSensing/AddTemperatureData',
            Temperature__pb2.TemperatureData.SerializeToString,
            Temperature__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
